// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var K, N, data, i, j, links, nodes, params, _i, _j, _k;
    params = getParams();
    if (params.N) {
      $("#N").val(params.N);
    }
    if (params.K) {
      $("#K").val(params.K);
    }
    N = params.N || 100;
    K = params.K || 3;
    console.log(N, K);
    nodes = [];
    for (i = _i = 0; 0 <= N ? _i < N : _i > N; i = 0 <= N ? ++_i : --_i) {
      nodes.push({
        "name": i,
        "group": 1
      });
    }
    links = [];
    for (i = _j = 0; 0 <= N ? _j < N : _j > N; i = 0 <= N ? ++_j : --_j) {
      for (j = _k = 0; 0 <= i ? _k < i : _k > i; j = 0 <= i ? ++_k : --_k) {
        if (Math.random() < K / N) {
          links.push({
            "source": i,
            "target": j,
            "value": 1
          });
        }
      }
    }
    data = {
      nodes: nodes,
      links: links
    };
    return draw(N, K, data);
  });

}).call(this);
